### ISSUE TITLE
1.2.4 don't see setting when arrive in cmp

### ISSUE THREAD

**Issue by Mabol** [Jako/CrossContextsSettings#3] opened 2023-03-11 19:00 UTC
hello
modx 3.0.3, CrossCS 1.2.4, now i change everything except the key :)
is not a big problem but
when i arrive in cmp the first time i don't see anything
![Clipboard01](https://user-images.githubusercontent.com/5990867/224506671-32f8a8b6-9ab1-4f09-8346-9119c342f0fa.jpg)
i see every thing if i clear the filter
![Clipboard02](https://user-images.githubusercontent.com/5990867/224506701-1ecef0e4-ad30-45b4-ba2b-b6e34f02f087.jpg)
or i select a specific namespace
![Clipboard03](https://user-images.githubusercontent.com/5990867/224506716-ae5625b9-1d40-4278-b352-4df0521989b6.jpg)

**Comment by Jako** [comment] 2023-03-11 19:12
Sorry, I can't reproduce that here on my dev machine and on a installation of a client too.

**Comment by Jako** [comment] 2023-03-11 19:47
It should only occur if you open the settings tab (cog icon) and then open the context settings tab. This will be fixed in the next version.

**Closed as completed by Jako** 2023-03-11 19:47 UTC

**Comment by Jako** [comment] 2023-03-11 20:31
I have uploaded a fixed 1.2.4 version.
